novaway_feature_flag:
    features:
        api:
            enabled: true

        subscription:
            enabled: true

        admin:
            enabled: true

        processor:
            enabled: true

        amplifier:
            enabled: true

        speaker:
            enabled: true

        chassis:
            enabled: true

        manufacturers:
            enabled: true

        limiter:
            enabled: true