twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        tourButton: false
        app_version: '%env(APP_VERSION)%'

when@test:
    twig:
        strict_variables: true
